{
 "title": "NYC Green Data",
 "time": { "from": "2022-02-20T22:40:05.253Z", "to": "2022-02-28T20:53:25.551Z" },
 "panels": [
  {
   "title": "NYC green taxi data",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Drifted Column",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}